controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.5
      movement_time_allowance: 10.0
    # Goal checker parameters
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.25
      stateful: True

    FollowPath:

      plugin: nav2_rotation_shim_controller::RotationShimController
      angular_dist_threshold: 0.785
      #angular_disengage_threshold: 0.3925
      forward_sampling_distance: 0.3
      rotate_to_heading_angular_vel: 3.6
      max_angular_accel: 20.0
      simulate_ahead_time: 0.3
      rotate_to_goal_heading: false
      primary_controller: nav2_social_mpc_controller::SocialMPCController
      trajectorizer:
        omnidirectional: false
        desired_linear_vel: 0.6
        lookahead_dist: 1.0
        max_angular_vel: 1.4
        transform_tolerance: 0.5
        base_frame: "base_link"
        time_step: 0.05
        max_time: 1.5
      optimizer:
        linear_solver_type: "DENSE_SCHUR"
        param_tol: 1.0e-9
        fn_tol: 1.0e-5
        gradient_tol: 1.0e-8
        max_iterations: 40
        control_horizon: 18
        parameter_block_length: 6
        discretization: 1
        debug_optimizer: false
        current_path_weight: 1.0
        current_cmds_weight: 0.5
        weights:
          distance_weight: 20.0
          social_weight: 0.0 #400.0
          velocity_weight: 10.0
          angle_weight: 300.0
          agent_angle_weight: 40.0 #50.0
          proxemics_weight: 80.0
          velocity_feasibility_weight: 5.0
          goal_align_weight: 10.0
          obstacle_weight: 0.13
          #obstacle_weight: 0.000005